name: Core

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Write key
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
        else
          echo "secrets.KEY_STORE not set"
        fi
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          !~/.gradle/caches/build-cache-*
        key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          gradle-deps
    - name: Cache Gradle Build
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/build-cache-*
        key: gradle-builds-core-${{ github.sha }}
        restore-keys: |
          gradle-builds
    - name: Cache Ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-cache-${{ github.sha }}
        restore-keys: ccache-cache-
    - name: Install ccache
      run: |
        sudo apt-get install -y ccache
        ccache -o max_size=1G
        ccache -o hash_dir=false
        ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
        ccache -zp
    - name: Build with Gradle
      env:
        NDK_CCACHE: ccache
      run: |
        [ $(du -s ~/.gradle/wrapper | awk '{ print $1 }') -gt 250000 ] && rm -rf ~/.gradle/wrapper/* || true
        find ~/.gradle/caches -exec touch -d "2 days ago" {} + || true
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        echo 'android.native.buildOutput=verbose' >> gradle.properties
        ./gradlew zipAll
        ccache -s
    - name: Prepare artifact
      if: success()
      id: prepareArtifact
      run: |
        riruReleaseName=`ls core/release/LSPosed-riru-v*-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=riruReleaseName::$riruReleaseName"
        riruDebugName=`ls core/release/LSPosed-riru-v*-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=riruDebugName::$riruDebugName"
        zygiskReleaseName=`ls core/release/LSPosed-zygisk-v*-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=zygiskReleaseName::$zygiskReleaseName"
        zygiskDebugName=`ls core/release/LSPosed-zygisk-v*-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "::set-output name=zygiskDebugName::$zygiskDebugName"
        unzip core/release/LSPosed-riru-v*-release.zip -d LSPosed-riru-release
        unzip core/release/LSPosed-riru-v*-debug.zip -d LSPosed-riru-debug
        unzip core/release/LSPosed-zygisk-v*-release.zip -d LSPosed-zygisk-release
        unzip core/release/LSPosed-zygisk-v*-debug.zip -d LSPosed-zygisk-debug
    - name: Upload riru release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.riruReleaseName }}
        path: './LSPosed-riru-release/*'
    - name: Upload riru debug
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.riruDebugName }}
        path: './LSPosed-riru-debug/*'
    - name: Upload zygisk release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
        path: './LSPosed-zygisk-release/*'
    - name: Upload zygisk debug
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
        path: './LSPosed-zygisk-debug/*'
    - name: Upload mappings
      uses: actions/upload-artifact@v2
      with:
        name: mappings
        path: |
          core/build/outputs/mapping/release
          app/build/outputs/mapping/release
